export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_BULK_UPLOAD_REQUEST = "PRODUCT_BULK_UPLOAD_REQUEST";
export const PRODUCT_BULK_UPLOAD_SUCCESS = "PRODUCT_BULK_UPLOAD_SUCCESS";
export const PRODUCT_BULK_UPLOAD_FAIL = "PRODUCT_BULK_UPLOAD_FAIL";
export const PRODUCT_BULK_UPLOAD_RESET = "PRODUCT_BULK_UPLOAD_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUCT_UPDATE_RESET";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const REVIEW_LIST_REQUEST = "REVIEW_LIST_REQUEST";
export const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";
export const REVIEW_LIST_FAIL = "REVIEW_LIST_FAIL";

export const REVIEW_APPROVE_REQUEST = "REVIEW_APPROVE_REQUEST";
export const REVIEW_APPROVE_SUCCESS = "REVIEW_APPROVE_SUCCESS";
export const REVIEW_APPROVE_FAIL = "REVIEW_APPROVE_FAIL ";


// productConstants.js
export const PRODUCT_CUSTOMIZE_REQUEST = 'PRODUCT_CUSTOMIZE_REQUEST'
export const PRODUCT_CUSTOMIZE_SUCCESS = 'PRODUCT_CUSTOMIZE_SUCCESS'
export const PRODUCT_CUSTOMIZE_FAIL = 'PRODUCT_CUSTOMIZE_FAIL'

export const PRODUCT_SAVE_CUSTOMIZATION_REQUEST = 'PRODUCT_SAVE_CUSTOMIZATION_REQUEST'
export const PRODUCT_SAVE_CUSTOMIZATION_SUCCESS = 'PRODUCT_SAVE_CUSTOMIZATION_SUCCESS'
export const PRODUCT_SAVE_CUSTOMIZATION_FAIL = 'PRODUCT_SAVE_CUSTOMIZATION_FAIL'

export const PRODUCT_GET_CUSTOMIZATIONS_REQUEST = 'PRODUCT_GET_CUSTOMIZATIONS_REQUEST'
export const PRODUCT_GET_CUSTOMIZATIONS_SUCCESS = 'PRODUCT_GET_CUSTOMIZATIONS_SUCCESS'
export const PRODUCT_GET_CUSTOMIZATIONS_FAIL = 'PRODUCT_GET_CUSTOMIZATIONS_FAIL'

export const PRODUCT_APPROVE_CUSTOMIZATION_REQUEST = 'PRODUCT_APPROVE_CUSTOMIZATION_REQUEST'
export const PRODUCT_APPROVE_CUSTOMIZATION_SUCCESS = 'PRODUCT_APPROVE_CUSTOMIZATION_SUCCESS'
export const PRODUCT_APPROVE_CUSTOMIZATION_FAIL = 'PRODUCT_APPROVE_CUSTOMIZATION_FAIL'